### ISSUE TITLE
PHP Composer - deploying packages

### ISSUE THREAD

**Issue by dan-burt** [ikknd/docker-study#2]
Hi.

I enjoyed the `recipe 05` article about using `composer` within a container.

I am struggling getting 2 packages installed within my PHP container:
 - mongodb/mongodb
 - vlucas/phpdotenv

I started building this INSIDE the container (as you mention in Stage 1 - bad idea...) and I have the mongodb client / SDK working, though I had to hardcode some references to the `usr/bin` directory, rather than in the webserver's "root" directory (`/var/www/html`) - this was following some other guide which did the same. I actually keep this currently in a sub-folder and use `docker-compose up -d` to bring up the container. The mapping is:
```
    volumes:
      - ./html:/var/www/html
```

This however breaks now I want to use the 2nd package.

If I map an existing folder, with all my PHP pages & scripts, it doesn't work. If I omit this mapping, I can see that the packages seem to be installed, however my files are no longer there.

Searching around, I found your article and I am stuck at how to deploy the packages AND allow me to map my existing folder. What order does your setup execute? I am guessing the `composer` container completes the installs to it's `/app` local directory. This same directory is mapped to the `php` container, but how does it handle overwrites or which 1 is executed first? 

Can I ask how you overcome this, as your mapped root folder only contains the `composer.json` file?

**Comment by ikknd** [comment]
Hi,
Composer installs all the code in /vendor folder, and in this case it does not matter in which order containers are executed, as they would not overwrite any files.
Try to clone my repository, and change composer.json file in recipe-05, to the 2 packages that you need.
You will see that index.php file is still there, but also new packages were installed in /vendor folder

**Comment by dan-burt** [comment]
Thanks - I have tried a few ways to deploy this, including basing from your own `docker-compose.yml` file, such as:

```
version: '2'

services:
  php:
    image: php:8.0-apache
    container_name: php
    volumes:
      - ./html:/var/www/html
    restart: always
    environment:
      - VIRTUAL_HOST=www.domain.com
      - LETSENCRYPT_HOST=www.domain.com
      - LETSENCRYPT_EMAIL=admin@domain.com
      - "TZ=Europe/London"
    ports:
      - 80
    expose:
      - 80
    restart: unless-stopped

  composer:
    image: composer:2.0
    command: ["composer", "install"]
    volumes:
      - ./html:/app

networks:
  default:
    external:
      name: nginx-proxy-net
```

When this starts, the `composer` container's log contains:

> No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.,
> Loading composer repositories with package information,
> Updating dependencies,
> Your requirements could not be resolved to an installable set of packages.,
> ,
>   Problem 1,
>     - Root composer.json requires mongodb/mongodb ^1.8.0 -> satisfiable by mongodb/mongodb[1.8.0].,
>     - mongodb/mongodb 1.8.0 requires ext-mongodb ^1.8.1 -> it is missing from your system. Install or enable PHP's mongodb extension.,
> ,
> To enable extensions, verify that they are enabled in your .ini files:,
>     - /usr/local/etc/php/php-cli.ini,
>     - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
>     - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini,
> You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.,
> 

It is complaining about the `mongodb` package, obviously. So if I revert to a custom image I have been working on, Dockerfile:

```
FROM php:8.0-apache

RUN apt-get update -y && apt-get upgrade -y && apt-get install git libssl-dev -y
RUN pecl install mongodb && docker-php-ext-enable mongodb
RUN echo "extension=mongodb.so" >> /usr/local/etc/php/php.ini
COPY --from=composer /usr/bin/composer /usr/bin/composer

EXPOSE 80 443
```

And then change `docker-compose.yml` & rebuild the container to use this image instead (`redswitch/php-mongodb:8.0-1.9.0`), the `mongodb` extension is deployed with version `1.9.0` - I can verify this with a `phpinfo()` call (have a `phpinfo.php` page with just this command). However the **same** message is listed in the `composer` container, so it is not fully deploying the `mongodb` extension or enabling it...

If I remove the `mongodb/mongodb` line from `composer.json`, the other package installs as expected under the `./html/vendor` location, however I cannot connect to the MongoDB database.
